export const foodImageList = [
  // 'carlos.jpg',
  // 'deepa.jpg',
  'dylan.jpg',
  'elena.jpg',
  'eun.jpg',
  'george.jpg',
  'georgina.jpg',
  'izzy.jpg',
  'james.jpg',
  'laurie.jpg',
  'matt.jpg',
  'nick.jpg',
  'shaughn.jpg',
  'tess.jpg',
  'tomaso.jpg',
  'yuqing.jpg',
]
